# Generated by Django 5.0.6 on 2024-05-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='candidate',
            name='party_image_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='candidate',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
